User.create(first_name: 'Matt', last_name: 'Baker', email: 'mattbaker@dbc.com', username: 'bakerROX', password_hash: 'password')

KitchenList.create(user_id: 1)

Category.create(name: 'Dairy')
Category.create(name: 'Produce')
Category.create(name: 'Beverages')
Category.create(name: 'Meat')
Category.create(name: 'Bakery')
Category.create(name: 'Pantry')
Category.create(name: 'Frozen')

Ingredient.create(name: 'skim milk', kitchen_list_id: 1, category_id: 1)
Ingredient.create(name: 'whole milk', kitchen_list_id: 1, category_id: 1)
Ingredient.create(name: 'apples', kitchen_list_id: 1, category_id: 2)
Ingredient.create(name: 'broccoli', kitchen_list_id: 1, category_id: 2)
Ingredient.create(name: 'oranges', kitchen_list_id: 1, category_id: 2)
Ingredient.create(name: 'spinach', kitchen_list_id: 1, category_id: 2)
Ingredient.create(name: 'tonic water', kitchen_list_id: 1, category_id: 3)
Ingredient.create(name: 'gatorade', kitchen_list_id: 1, category_id: 3)
Ingredient.create(name: 'ground beef', kitchen_list_id: 1, category_id: 4)
Ingredient.create(name: 'chicken thighs', kitchen_list_id: 1, category_id: 4)
Ingredient.create(name: 'pork loin', kitchen_list_id: 1, category_id: 4)
Ingredient.create(name: 'bagels', kitchen_list_id: 1, category_id: 5)
Ingredient.create(name: 'salt', kitchen_list_id: 1, category_id: 6)
Ingredient.create(name: 'pepper', kitchen_list_id: 1, category_id: 6)
Ingredient.create(name: 'flour', kitchen_list_id: 1, category_id: 6)
Ingredient.create(name: 'olive oil', kitchen_list_id: 1, category_id: 6)
Ingredient.create(name: 'pizza', kitchen_list_id: 1, category_id: 7)

Recipe.create(name: 'Apple Pie', description: 'Serve a la mode with ice cream!', user_id: 1)
